module Azurite
  module Constants
    CONTENT_RETENTION_DAYS = 45
    CONTENT_DB_MAX_SIZE_MB = 50
    CONTENT_DB_HARD_LIMIT_MB = 100
    CONTENT_DB_WARNING_MB = 30
    CONTENT_MAX_SIZE_BYTES = 1_048_576
    CONTENT_DB_NAME = "content.db"
  end
end