# Embeds the compiled elm.js into Crystal source code
# Run this after: elm make src/Main.elm --output=public/elm.js

require "json"

module ElmEmbedder
  VERSION = "1.0.0"

  ELM_JS_PATH = "public/elm.js"
  OUTPUT_PATH = "src/embedded_elm.cr"
  CONSTANT_NAME = "ELM_JS"

  def self.run
    puts "Elm Embedder v#{VERSION}"
    puts "-" * 40

    unless File.exists?(ELM_JS_PATH)
      puts "Error: #{ELM_JS_PATH} not found!"
      puts "Run: elm make src/Main.elm --output=#{ELM_JS_PATH}"
      exit 1
    end

    puts "Reading #{ELM_JS_PATH}..."
    elm_js_content = File.read(ELM_JS_PATH)

    puts "Embedding as Crystal string constant..."
    embedded = embed_as_crystal(elm_js_content)

    puts "Writing to #{OUTPUT_PATH}..."
    File.write(OUTPUT_PATH, embedded)

    puts "-" * 40
    puts "Success! Embedded #{elm_js_content.size} bytes"
    puts "Add 'require \"./embedded_elm\"' to your main Crystal file"
  end

  private def embed_as_crystal(content : String) : String
    # Escape special characters for Crystal string
    escaped = content
      .gsub("\\", "\\\\")          # Escape backslashes
      .gsub("\"", "\\\"")          # Escape quotes
      .gsub("\n", "\\n")           # Escape newlines
      .gsub("\r", "\\r")           # Escape carriage returns
      .gsub("\t", "\\t")           # Escape tabs

    <<-CRYSTAL
    # This file is auto-generated by scripts/embed_elm.cr
    # DO NOT EDIT MANUALLY

    # Elm JavaScript bundle embedded for single-binary deployment
    module EmbeddedElm
      VERSION = "1.0.0"

      # The compiled Elm application JavaScript
      def self.js : String
        <<-'ELM_JS'
    #{escaped}
        ELM_JS
      end

      # Returns the content type for the JavaScript
      def self.content_type : String
        "application/javascript; charset=utf-8"
      end

      # Returns the file size in bytes
      def self.size : Int64
        js.bytesize.to_i64
      end
    end
    CRYSTAL
  end
end

ElmEmbedder.run
