#!/bin/sh
# Generate a launch wrapper that bakes the devshell LD_LIBRARY_PATH, so the
# Nim binary runs directly without `nix develop` (which re-evaluates the flake
# on every launch - the main source of startup delay).
#
# usage: nim-wrap.sh <wrapper-path> <binary-path> <ld_library_path>
set -eu
wrapper="$1"
bin="$2"
ldlp="$3"
cat > "$wrapper" <<EOF
#!/bin/sh
# Auto-generated by scripts/nim-wrap.sh - do not edit.
# Bakes devshell LD_LIBRARY_PATH so this runs without a slow nix develop.
export LD_LIBRARY_PATH="$ldlp"
exec "\$(dirname "\$0")/$(basename "$bin")" "\$@"
EOF
chmod +x "$wrapper"
echo "wrote wrapper $wrapper -> $bin"
