module QuickHeadlines::Constants
  CONCURRENCY               =   8
  CACHE_RETENTION_HOURS     = 168
  CACHE_RETENTION_DAYS      = CACHE_RETENTION_HOURS // 24
  DB_SIZE_WARNING_THRESHOLD = 50 * 1024 * 1024
  DB_SIZE_HARD_LIMIT        = 100 * 1024 * 1024
  DB_VACUUM_THRESHOLD       = 10 * 1024 * 1024
  DB_TIME_FORMAT            = "%Y-%m-%d %H:%M:%S"

  HTTP_CONNECT_TIMEOUT   =   10
  HTTP_READ_TIMEOUT      =   30
  HTTP_WRITE_TIMEOUT     =   10
  FETCH_TIMEOUT_SECONDS  =   60
  MAX_REDIRECTS          =   10
  MAX_RETRIES            =    3
  MAX_BACKOFF_SECONDS    =   60
  MAX_CONNECTIONS        = 1000
  MAX_CONNECTIONS_PER_IP =   10
  STALE_CONNECTION_AGE   =  120
  CONNECTION_QUEUE_SIZE  =  100

  SECONDS_PER_MINUTE      =  60
  CACHE_FRESHNESS_MINUTES =   5
  FETCH_BUFFER_ITEMS      =  50
  BROADCAST_TIMEOUT_MS    = 100

  AGGRESSIVE_CLEANUP_DAYS      =   3
  VERY_AGGRESSIVE_CLEANUP_DAYS =   1
  MIN_DB_SIZE_BYTES            = 100

  MAX_REQUEST_BODY_SIZE = 1_048_576

  MAX_PARALLEL_CLUSTERING    =   6
  CLUSTERING_TIMEOUT_SECONDS = 300
  FEED_FETCH_TIMEOUT_SECONDS = 300

  RATE_LIMITER_INSTANCE_TTL     = 3600
  RATE_LIMITER_CLEANUP_INTERVAL =   60

  FAVICON_MAX_SIZE           = 100 * 1024
  FAVICON_HASH_PREFIX_LENGTH = 16

  COLOR_CACHE_MAX_SIZE    = 1000
  COLOR_CACHE_EXPIRY_DAYS =    7

  WEBSOCKET_CHANNEL_SIZE      = 100
  WEBSOCKET_HEARTBEAT_SECONDS =  30
  WEBSOCKET_SEND_TIMEOUT_MS   =  10

  JANITOR_INTERVAL        = 60.seconds
  CLUSTERING_INTERVAL     = 60.minutes
  CLEANUP_INTERVAL        = 6.hours
  WS_JANITOR_INTERVAL     = 5.minutes
  INITIAL_CLUSTER_DELAY   = 30.seconds
  STUCK_CLUSTER_THRESHOLD = 4.hours

  CACHE_ONE_YEAR = 31536000
  CACHE_ONE_HOUR =     3600

  PROXY_DEFAULT_MAX_BYTES = 2 * 1024 * 1024

  SQLITE_BUSY_TIMEOUT_MS = 30000

  NORMALIZE_BATCH_SIZE =  500
  MAX_FEED_ITEMS_LOAD  = 1000
  DB_MAX_POOL_SIZE     =   12
  # WAL checkpoint threshold - smaller value = more frequent checkpoints = less WAL growth
  WAL_AUTOCHECKPOINT_PAGES = 1000

  CLUSTER_TITLE_TRUNCATE_LENGTH = 50

  ALLOWED_PROXY_DOMAINS = {
    "i.imgur.com",
    "pbs.twimg.com",
    "avatars.githubusercontent.com",
    "lh3.googleusercontent.com",
    "i.pravatar.cc",
    "images.unsplash.com",
    "fastly.picsum.photos",
  }
end
